"use client";
import { useState, useEffect } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import InputGroup from '@/components/ui/InputGroup';
import { calculateLumpsum, formatCurrency } from '@/utils/formulas';
import SaveReportButton from '@/components/SaveReportButton';
import { ArrowLeft, TrendingUp, Wallet, ArrowUpRight, Download, PieChart } from 'lucide-react';
import dynamic from 'next/dynamic';
import { Pie } from 'react-chartjs-2';
import {
    Chart as ChartJS,
    ArcElement,
    Tooltip,
    Legend
} from 'chart.js';

ChartJS.register(ArcElement, Tooltip, Legend);

export default function LumpsumCalculator() {
    const searchParams = useSearchParams();
    const [investment, setInvestment] = useState(100000);
    const [rate, setRate] = useState(12);
    const [years, setYears] = useState(10);
    const [result, setResult] = useState<any>(null);

    useEffect(() => {
        const pInvestment = searchParams.get('investment');
        const pRate = searchParams.get('rate');
        const pYears = searchParams.get('years');

        if (pInvestment) setInvestment(Number(pInvestment));
        if (pRate) setRate(Number(pRate));
        if (pYears) setYears(Number(pYears));
    }, [searchParams]);

    useEffect(() => {
        const data = calculateLumpsum(investment, rate, years);
        setResult(data);
    }, [investment, rate, years]);

    const chartData = {
        labels: ['Invested Amount', 'Wealth Gained'],
        datasets: [{
            data: [result?.breakdown.invested, result?.breakdown.gained],
            backgroundColor: ['#ffffff40', '#ffffff'],
            borderWidth: 0,
        }],
    };

    // --- PDF Download Logic (via HTML Print) ---
    const handleDownloadReport = () => {
        if (!result || !result.schedule || result.schedule.length === 0) {
            alert("Please calculate a result before generating the report.");
            return;
        }

        const { breakdown, schedule } = result;

        let tableRows = '';
        schedule.forEach((item: any) => {
            tableRows += `
            <tr style="border-bottom: 1px solid #eee;">
                <td style="padding: 12px; text-align: center;">${item.year}</td>
                <td style="padding: 12px; text-align: right;">₹ ${investment.toLocaleString('en-IN')}</td>
                <td style="padding: 12px; text-align: right; color: #059669;">₹ ${item.gain.toLocaleString('en-IN')}</td>
                <td style="padding: 12px; text-align: right; font-weight: bold;">₹ ${item.value.toLocaleString('en-IN')}</td>
            </tr>
        `;
        });

        const reportHTML = `
        <!DOCTYPE html>
        <html>
        <head>
            <title>Lumpsum Growth Report</title>
            <style>
                body { font-family: sans-serif; margin: 0; padding: 40px; color: #333; }
                .header { background-color: #f0fdf4; padding: 20px; border-radius: 8px; margin-bottom: 30px; border-left: 5px solid #10b981; }
                .summary { display: flex; justify-content: space-between; gap: 20px; margin-bottom: 40px; }
                .summary-card { padding: 20px; border-radius: 8px; flex: 1; border: 1px solid #ddd; }
                .title { font-size: 24px; font-weight: bold; color: #059669; margin-bottom: 5px; }
                .date { font-size: 12px; color: #666; }
                h2 { font-size: 18px; color: #1f2937; border-bottom: 2px solid #059669; padding-bottom: 5px; margin-bottom: 20px; margin-top: 30px; }
                table { width: 100%; border-collapse: collapse; font-size: 14px; }
                th { background-color: #e5e7eb; padding: 10px; text-align: right; color: #4b5563; font-weight: bold; border-bottom: 2px solid #333; }
                th:first-child { text-align: center; }
                .footer { margin-top: 50px; border-top: 1px solid #ccc; padding-top: 15px; font-size: 12px; color: #666; text-align: center; }

                @media print {
                    .no-print { display: none; }
                    body { box-shadow: none; margin: 0; padding: 0; }
                }
            </style>
        </head>
        <body>
            <div class="header">
                <div class="title">Lumpsum Investment Report</div>
                <div class="date">Generated by FineCalcs on: ${new Date().toLocaleDateString()}</div>
                <div style="font-size: 14px; margin-top: 10px;">Initial Investment: ₹ ${investment.toLocaleString('en-IN')} | Rate: ${rate}% | Tenure: ${years} Years</div>
            </div>

            <h2>Final Investment Summary</h2>
            <div class="summary">
                <div class="summary-card" style="border-color: #d1d5db;">
                    <p style="font-size: 14px; color: #666; margin-bottom: 5px;">Total Invested</p>
                    <p style="font-size: 28px; font-weight: bold; color: #1f2937;">₹ ${breakdown.invested.toLocaleString('en-IN')}</p>
                </div>
                <div class="summary-card" style="border-color: #a7f3d0; background-color: #f0fdf4;">
                    <p style="font-size: 14px; color: #059669; margin-bottom: 5px;">Wealth Gained (Returns)</p>
                    <p style="font-size: 28px; font-weight: bold; color: #059669;">₹ ${breakdown.gained.toLocaleString('en-IN')}</p>
                </div>
                <div class="summary-card" style="border-color: #34d399; background-color: #ecfdf5;">
                    <p style="font-size: 14px; color: #065f46; margin-bottom: 5px;">Final Corpus Value</p>
                    <p style="font-size: 30px; font-weight: bolder; color: #065f46;">₹ ${breakdown.total.toLocaleString('en-IN')}</p>
                </div>
            </div>

            <h2>Yearly Growth Schedule (Compounding Effect)</h2>
            <table>
                <thead>
                    <tr>
                        <th style="width: 10%;">Year</th>
                        <th style="width: 30%;">Initial Principal (₹)</th>
                        <th style="width: 30%;">Total Gain (₹)</th>
                        <th style="width: 30%;">Total Value (₹)</th>
                    </tr>
                </thead>
                <tbody>
                    ${tableRows}
                </tbody>
            </table>

            <div class="footer">
                This report is for informational and educational purposes only. Always consult a certified financial advisor before making investment decisions.
            </div>

            <div class="no-print" style="margin-top: 40px; text-align: center; background: #fff; padding: 20px; border: 1px dashed #ccc;">
                <p><strong>To save as PDF:</strong> Please use your browser's print function (Ctrl+P or Cmd+P) and select "Save as PDF" as the destination.</p>
            </div>
        </body>
        </html>
    `;

        const printWindow = window.open('', '', 'height=600,width=800');
        if (printWindow) {
            printWindow.document.write(reportHTML);
            printWindow.document.close();
            printWindow.onload = () => {
                printWindow.focus();
                printWindow.print();
            };
        }
    };
    // --- END PDF Download Logic ---


    return (
        <div className="min-h-screen bg-slate-50 dark:bg-slate-950 py-12 font-sans transition-colors duration-300">
            <div className="max-w-5xl mx-auto px-4">
                <Link href="/" className="inline-flex items-center text-sm font-bold text-slate-400 hover:text-emerald-600 dark:hover:text-emerald-400 mb-8 transition-colors group">
                    <ArrowLeft className="w-4 h-4 mr-1 group-hover:-translate-x-1 transition-transform" /> Back to Home
                </Link>

                <div className="grid grid-cols-1 xl:grid-cols-12 gap-8">
                    {/* LEFT: Input Section */}
                    <div className="xl:col-span-5 space-y-6">
                        <div>
                            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400 text-xs font-extrabold mb-4 uppercase tracking-wide">
                                <PieChart className="w-3 h-3" /> One-Time Growth
                            </div>
                            <h1 className="text-4xl font-black text-slate-900 dark:text-white mb-3 tracking-tight">Lumpsum Calculator</h1>
                            <p className="text-slate-500 dark:text-slate-400 font-medium leading-relaxed">
                                Calculate the future value of a single, one-time investment over a long duration.
                            </p>
                        </div>

                        <div className="bg-white dark:bg-slate-900 p-8 rounded-3xl shadow-xl shadow-slate-200/60 dark:shadow-none border border-slate-100 dark:border-slate-800 transition-colors">
                            <InputGroup
                                label="Initial Investment (Principal)"
                                value={investment}
                                onChange={setInvestment}
                                type="currency"
                                min={1000} max={5000000} step={1000}
                                variant="green"
                            />
                            <InputGroup
                                label="Expected Return (p.a)"
                                value={rate}
                                onChange={setRate}
                                type="percentage"
                                min={1} max={30} step={0.1}
                                variant="green"
                            />
                            <InputGroup
                                label="Time Period"
                                value={years}
                                onChange={setYears}
                                type="year"
                                min={1} max={50} step={1}
                                variant="green"
                            />

                            <div className="flex gap-3 mt-6">
                                <SaveReportButton
                                    reportData={{ ...result, inputs: { investment, rate, years } }}
                                    calculatorType="Lumpsum Calculator"
                                    disabled={!result}
                                />
                                <button
                                    onClick={handleDownloadReport}
                                    className="flex-1 inline-flex items-center justify-center gap-2 px-4 py-2.5 bg-slate-100 dark:bg-slate-800 text-slate-800 dark:text-white font-bold rounded-xl hover:bg-slate-200 dark:hover:bg-slate-700 transition-all text-sm"
                                >
                                    <Download className="w-4 h-4" /> Download
                                </button>
                            </div>

                        </div>
                    </div>

                    {/* RIGHT: Result Section */}
                    <div className="xl:col-span-7 space-y-6">
                        <div className="bg-emerald-900 rounded-3xl p-8 sm:p-12 relative overflow-hidden shadow-2xl shadow-emerald-900/40 border border-emerald-800">
                            <div className="absolute top-0 right-0 -mt-20 -mr-20 w-80 h-80 bg-emerald-300 opacity-20 rounded-full blur-3xl animate-pulse"></div>
                            <div className="absolute bottom-0 left-0 -mb-20 -ml-20 w-80 h-80 bg-teal-900 opacity-20 rounded-full blur-3xl"></div>

                            <div className="relative z-10 grid grid-cols-1 xl:grid-cols-2 gap-8 xl:gap-12 items-center">
                                <div className="w-full">
                                    <p className="text-emerald-100 font-semibold mb-2 tracking-wide text-xs sm:text-sm uppercase">Total Maturity Value</p>
                                    <p className="text-4xl sm:text-5xl xl:text-5xl font-black tracking-tighter mb-8 drop-shadow-sm leading-tight">
                                        {formatCurrency(result?.breakdown.total || 0)}
                                    </p>

                                    <div className="space-y-3 sm:space-y-4">
                                        <div className="bg-white/10 backdrop-blur-md rounded-2xl p-4 sm:p-5 border border-white/10 hover:bg-white/20 transition-colors">
                                            <div className="flex items-center gap-3 mb-1">
                                                <div className="p-1.5 bg-white/20 rounded-lg">
                                                    <Wallet className="w-4 h-4 text-white" />
                                                </div>
                                                <span className="text-xs sm:text-sm font-bold text-emerald-50">Invested Principal</span>
                                            </div>
                                            <p className="text-xl sm:text-2xl font-bold ml-9 sm:ml-10 tracking-tight">{formatCurrency(result?.breakdown.invested || 0)}</p>
                                        </div>

                                        <div className="bg-emerald-900/20 backdrop-blur-md rounded-2xl p-4 sm:p-5 border border-white/5 hover:bg-emerald-900/30 transition-colors">
                                            <div className="flex items-center gap-3 mb-1">
                                                <div className="p-1.5 bg-emerald-400/20 rounded-lg">
                                                    <ArrowUpRight className="w-4 h-4 text-emerald-200" />
                                                </div>
                                                <span className="text-xs sm:text-sm font-bold text-emerald-100">Wealth Gained</span>
                                            </div>
                                            <p className="text-xl sm:text-2xl font-bold ml-9 sm:ml-10 text-emerald-200 tracking-tight">{formatCurrency(result?.breakdown.gained || 0)}</p>
                                        </div>
                                    </div>
                                </div>

                                <div className="flex flex-col items-center justify-center bg-white/5 rounded-3xl p-6 sm:p-8 backdrop-blur-sm border border-white/10 shadow-inner w-full max-w-sm mx-auto xl:mx-0">
                                    <div className="w-40 h-40 sm:w-48 sm:h-48 relative">
                                        <Pie data={chartData} options={{
                                            plugins: { legend: { display: false } },
                                            elements: { arc: { borderWidth: 0 } },
                                            animation: { animateScale: true }
                                        }} />
                                    </div>
                                    <div className="mt-6 sm:mt-8 flex gap-4 sm:gap-6 text-xs sm:text-sm justify-center">
                                        <div className="flex items-center gap-2">
                                            <div className="w-3 h-3 rounded-full bg-white/40"></div>
                                            <span className="text-emerald-100 font-medium">Invested</span>
                                        </div>
                                        <div className="flex items-center gap-2">
                                            <div className="w-3 h-3 rounded-full bg-white shadow-[0_0_10px_rgba(255,255,255,0.5)]"></div>
                                            <span className="text-white font-bold">Returns</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {/* --- SEO/Content Section --- */}
                <div className="mt-20 max-w-3xl mx-auto">
                    <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">Lumpsum Investment Strategy</h2>
                    <p className="text-slate-600 dark:text-slate-400">Lumpsum investing is ideal for one-time capital that you want to put to work immediately. While volatile in the short term, over long periods, the compounding effect can be greater than SIPs due to higher upfront investment time.</p>
                </div>

            </div>
        </div>
    );
}