"use client";

import { useState, useEffect } from 'react';
import Link from 'next/link';
import InputGroup from '@/components/ui/InputGroup';
import SaveReportButton from '@/components/SaveReportButton';
import { calculateEMI, formatCurrency } from '@/utils/formulas';
import { Pie } from 'react-chartjs-2';
import { Chart as ChartJS, ArcElement, Tooltip, Legend } from 'chart.js';
import { ArrowLeft, Percent, Building2, CalendarClock, Download } from 'lucide-react';

ChartJS.register(ArcElement, Tooltip, Legend);

export default function EMICalculator() {
  const [loanAmount, setLoanAmount] = useState(5000000);
  const [rate, setRate] = useState(8.5);
  const [years, setYears] = useState(20);
  const [result, setResult] = useState<any>(null);

  useEffect(() => {
    // The calculateEMI function now generates the schedule internally
    const data = calculateEMI(loanAmount, rate, years);
    setResult(data);
  }, [loanAmount, rate, years]);

  const chartData = {
    labels: ['Principal Amount', 'Interest Payable'],
    datasets: [{
      data: [loanAmount, result?.totalInterest],
      backgroundColor: ['#ffffff40', '#ffffff'],
      borderWidth: 0,
    }],
  };

  // --- UPDATED: PDF Download Logic (via HTML Print) ---
  const handleDownloadReport = () => {
    if (!result || !result.schedule || result.schedule.length === 0) {
      alert("Please calculate a result before downloading the amortization report.");
      return;
    }

    const { monthlyEMI, totalInterest, totalPayment, schedule } = result;

    let tableRows = '';
    schedule.forEach((item: any) => {
      tableRows += `
            <tr style="border-bottom: 1px solid #eee; ${item.month % 12 === 0 ? 'background-color: #f3f4f6;' : ''}">
                <td style="padding: 12px; text-align: center;">${item.month}</td>
                <td style="padding: 12px; text-align: right;">₹ ${monthlyEMI.toLocaleString('en-IN')}</td>
                <td style="padding: 12px; text-align: right; color: #dc2626;">₹ ${item.interest.toLocaleString('en-IN')}</td>
                <td style="padding: 12px; text-align: right; color: #1f2937;">₹ ${item.principal.toLocaleString('en-IN')}</td>
                <td style="padding: 12px; text-align: right; font-weight: bold;">₹ ${item.balance.toLocaleString('en-IN')}</td>
            </tr>
        `;
    });

    const reportHTML = `
        <!DOCTYPE html>
        <html>
        <head>
            <title>Loan Amortization Report</title>
            <style>
                body { font-family: sans-serif; margin: 0; padding: 40px; color: #333; }
                .header { background-color: #fef2f2; padding: 20px; border-radius: 8px; margin-bottom: 30px; border-left: 5px solid #ef4444; }
                .summary { display: flex; justify-content: space-between; gap: 20px; margin-bottom: 40px; }
                .summary-card { padding: 20px; border-radius: 8px; flex: 1; border: 1px solid #ddd; }
                .title { font-size: 24px; font-weight: bold; color: #dc2626; margin-bottom: 5px; }
                .date { font-size: 12px; color: #666; }
                h2 { font-size: 18px; color: #1f2937; border-bottom: 2px solid #ef4444; padding-bottom: 5px; margin-bottom: 20px; margin-top: 30px; }
                table { width: 100%; border-collapse: collapse; font-size: 14px; }
                th { background-color: #f3f4f6; padding: 10px; text-align: right; color: #4b5563; font-weight: bold; border-bottom: 2px solid #333; }
                th:first-child { text-align: center; }
                .footer { margin-top: 50px; border-top: 1px solid #ccc; padding-top: 15px; font-size: 12px; color: #666; text-align: center; }
                
                @media print {
                    .no-print { display: none; }
                    body { box-shadow: none; margin: 0; padding: 0; }
                }
            </style>
        </head>
        <body>
            <div class="header">
                <div class="title">Loan Amortization Report</div>
                <div class="date">Generated by FineCalcs on: ${new Date().toLocaleDateString()}</div>
                <div style="font-size: 14px; margin-top: 10px;">Loan Amount: ₹ ${loanAmount.toLocaleString('en-IN')} | Rate: ${rate}% | Tenure: ${years} Years</div>
            </div>

            <h2>Loan Summary</h2>
            <div class="summary">
                <div class="summary-card" style="border-color: #d1d5db;">
                    <p style="font-size: 14px; color: #666; margin-bottom: 5px;">Monthly EMI</p>
                    <p style="font-size: 28px; font-weight: bold; color: #1f2937;">₹ ${monthlyEMI.toLocaleString('en-IN')}</p>
                </div>
                <div class="summary-card" style="border-color: #fca5a5; background-color: #fef2f2;">
                    <p style="font-size: 14px; color: #dc2626; margin-bottom: 5px;">Total Interest Paid</p>
                    <p style="font-size: 28px; font-weight: bold; color: #dc2626;">₹ ${totalInterest.toLocaleString('en-IN')}</p>
                </div>
                <div class="summary-card" style="border-color: #fb923c; background-color: #fff7ed;">
                    <p style="font-size: 14px; color: #c2410c; margin-bottom: 5px;">Total Payment (Principal + Interest)</p>
                    <p style="font-size: 30px; font-weight: bolder; color: #c2410c;">₹ ${totalPayment.toLocaleString('en-IN')}</p>
                </div>
            </div>

            <h2>Monthly Amortization Schedule</h2>
            <table>
                <thead>
                    <tr>
                        <th style="width: 10%;">Month</th>
                        <th style="width: 20%;">EMI (₹)</th>
                        <th style="width: 20%;">Interest (₹)</th>
                        <th style="width: 20%;">Principal (₹)</th>
                        <th style="width: 30%;">Outstanding Balance (₹)</th>
                    </tr>
                </thead>
                <tbody>
                    ${tableRows}
                </tbody>
            </table>

            <div class="footer">
                This report is for informational and educational purposes only. Interest calculations are based on monthly reducing balance.
            </div>

            <div class="no-print" style="margin-top: 40px; text-align: center; background: #fff; padding: 20px; border: 1px dashed #ccc;">
                <p><strong>To save as PDF:</strong> Please use your browser's print function (Ctrl+P or Cmd+P) and select "Save as PDF" as the destination.</p>
            </div>
        </body>
        </html>
    `;

    const printWindow = window.open('', '', 'height=600,width=800');
    if (printWindow) {
      printWindow.document.write(reportHTML);
      printWindow.document.close();
      printWindow.onload = () => {
        printWindow.focus();
        printWindow.print();
      };
    }
  };
  // --- END UPDATED Download Logic ---

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 py-12 font-sans transition-colors duration-300">
      <div className="max-w-5xl mx-auto px-4">
        <Link href="/" className="inline-flex items-center text-sm font-bold text-slate-400 hover:text-rose-600 dark:hover:text-rose-400 mb-8 transition-colors group">
          <ArrowLeft className="w-4 h-4 mr-1 group-hover:-translate-x-1 transition-transform" /> Back to Home
        </Link>

        <div className="grid grid-cols-1 xl:grid-cols-12 gap-8">

          <div className="xl:col-span-5 space-y-6">
            <div>
              <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-rose-100 dark:bg-rose-900/30 text-rose-700 dark:text-rose-400 text-xs font-extrabold mb-4 uppercase tracking-wide">
                <Building2 className="w-3 h-3" /> Loan Planner
              </div>
              <h1 className="text-4xl font-black text-slate-900 dark:text-white mb-3 tracking-tight">Home Loan EMI</h1>
              <p className="text-slate-500 dark:text-slate-400 font-medium leading-relaxed">
                Smartly plan your repayment. See how much interest you&apos;ll actually pay over 20 years.
              </p>
            </div>

            <div className="bg-white dark:bg-slate-900 p-8 rounded-3xl shadow-xl shadow-slate-200/60 dark:shadow-none border border-slate-100 dark:border-slate-800 transition-colors">
              <InputGroup
                label="Loan Amount"
                value={loanAmount}
                onChange={setLoanAmount}
                type="currency"
                min={100000} max={50000000} step={10000}
                variant="rose"
              />
              <InputGroup
                label="Interest Rate (%)"
                value={rate}
                onChange={setRate}
                type="percentage"
                min={1} max={20} step={0.1}
                variant="rose"
              />
              <InputGroup
                label="Loan Tenure"
                value={years}
                onChange={setYears}
                type="year"
                variant="rose"
              />

              <SaveReportButton
                reportData={{ ...result, inputs: { loanAmount, rate, years } }}
                calculatorType="EMI Calculator"
                disabled={!result}
              />

              <button
                onClick={handleDownloadReport}
                className="w-full mt-4 py-3 bg-rose-600 hover:bg-rose-700 text-white rounded-xl font-bold text-lg flex items-center justify-center gap-2 transition-all shadow-lg shadow-rose-500/30 hover:shadow-rose-500/50"
              >
                <Download className="w-5 h-5" />
                Download PDF Report
              </button>
            </div>
          </div>

          <div className="xl:col-span-7">
            <div className="bg-gradient-to-br from-rose-600 to-pink-700 rounded-[2.5rem] p-8 sm:p-10 text-white shadow-2xl shadow-rose-500/30 relative overflow-hidden transition-all duration-500 hover:shadow-rose-500/40 hover:scale-[1.01] h-full flex flex-col justify-center">
              <div className="absolute top-0 right-0 -mt-20 -mr-20 w-80 h-80 bg-white opacity-10 rounded-full blur-3xl animate-pulse"></div>
              <div className="absolute bottom-0 left-0 -mb-20 -ml-20 w-80 h-80 bg-black opacity-10 rounded-full blur-3xl"></div>

              <div className="relative z-10 grid grid-cols-1 xl:grid-cols-2 gap-8 xl:gap-12 items-center">
                <div className="w-full">
                  <p className="text-rose-100 font-semibold mb-2 tracking-wide text-xs sm:text-sm uppercase">Monthly EMI</p>
                  <p className="text-4xl sm:text-5xl xl:text-5xl font-black tracking-tighter mb-8 drop-shadow-sm leading-tight">
                    {formatCurrency(result?.monthlyEMI || 0)}
                  </p>

                  <div className="space-y-3 sm:space-y-4">
                    <div className="bg-white/10 backdrop-blur-md rounded-2xl p-4 sm:p-5 border border-white/10 hover:bg-white/20 transition-colors">
                      <div className="flex items-center gap-3 mb-1">
                        <div className="p-1.5 bg-white/20 rounded-lg">
                          <Building2 className="w-4 h-4 text-white" />
                        </div>
                        <span className="text-xs sm:text-sm font-bold text-rose-100">Principal</span>
                      </div>
                      <p className="text-xl sm:text-2xl font-bold ml-9 sm:ml-10 tracking-tight">{formatCurrency(loanAmount)}</p>
                    </div>

                    <div className="bg-rose-900/20 backdrop-blur-md rounded-2xl p-4 sm:p-5 border border-white/5 hover:bg-rose-900/30 transition-colors">
                      <div className="flex items-center gap-3 mb-1">
                        <div className="p-1.5 bg-orange-300/20 rounded-lg">
                          <Percent className="w-4 h-4 text-orange-200" />
                        </div>
                        <span className="text-xs sm:text-sm font-bold text-orange-100">Interest Payable</span>
                      </div>
                      <p className="text-xl sm:text-2xl font-bold ml-9 sm:ml-10 text-orange-200 tracking-tight">{formatCurrency(result?.totalInterest || 0)}</p>
                    </div>
                  </div>
                </div>

                <div className="flex flex-col items-center justify-center bg-white/5 rounded-3xl p-6 sm:p-8 backdrop-blur-sm border border-white/10 shadow-inner w-full max-w-sm mx-auto xl:mx-0">
                  <div className="w-40 h-40 sm:w-48 sm:h-48 relative">
                    <Pie data={chartData} options={{
                      plugins: { legend: { display: false } },
                      elements: { arc: { borderWidth: 0 } },
                      animation: { animateScale: true }
                    }} />
                  </div>
                  <div className="mt-6 sm:mt-8 flex gap-4 sm:gap-6 text-xs sm:text-sm justify-center">
                    <div className="flex items-center gap-2">
                      <div className="w-3 h-3 rounded-full bg-white/40"></div>
                      <span className="text-rose-100 font-medium">Principal</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="w-3 h-3 rounded-full bg-white shadow-[0_0_10px_rgba(255,255,255,0.5)]"></div>
                      <span className="text-white font-bold">Interest</span>
                    </div>
                  </div>
                </div>
              </div>

              <div className="mt-8 pt-8 border-t border-white/10 flex items-center justify-between text-sm text-rose-100 font-medium">
                <span>Total Payment: <strong className="text-white text-lg ml-1">{formatCurrency(result?.totalPayment || 0)}</strong></span>
                <span className="flex items-center gap-1.5 bg-black/10 px-3 py-1.5 rounded-full"><CalendarClock className="w-4 h-4" /> {years * 12} Months</span>
              </div>
            </div>
          </div>
        </div>

        {/* --- SEO/Content Section --- */}
        <div className="mt-20 max-w-3xl mx-auto">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">Understanding Loan Amortization</h2>
          <p className="text-slate-600 dark:text-slate-400">The detailed month-by-month amortization schedule, essential for tax planning and financial reviews, can be generated as a print-ready PDF using the "Generate PDF Report" button above.</p>
        </div>
      </div>
    </div>
  );
}