"use client";

import { useState, useEffect, Suspense } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import InputGroup from '@/components/ui/InputGroup';
import SaveReportButton from '@/components/SaveReportButton';
import { calculateFD, formatCurrency } from '@/utils/formulas';
import { Pie } from 'react-chartjs-2';
import { Chart as ChartJS, ArcElement, Tooltip, Legend } from 'chart.js';
import { ArrowLeft, TrendingUp, Wallet, ArrowUpRight, Download, Percent, ShieldCheck } from 'lucide-react';

ChartJS.register(ArcElement, Tooltip, Legend);

function FDCalculatorContent() {
  const searchParams = useSearchParams();
  const [investment, setInvestment] = useState(100000); // Default: 1 Lakh
  const [rate, setRate] = useState(7.0); // FD Rate
  const [years, setYears] = useState(5); // 5 Year Tenure
  const [result, setResult] = useState<any>(null);

  // Load from URL params if available
  useEffect(() => {
    const pInvestment = searchParams.get('investment');
    const pRate = searchParams.get('rate');
    const pYears = searchParams.get('years');

    if (pInvestment) setInvestment(Number(pInvestment));
    if (pRate) setRate(Number(pRate));
    if (pYears) setYears(Number(pYears));
  }, [searchParams]);

  useEffect(() => {
    const data = calculateFD(investment, rate, years);
    setResult(data);
  }, [investment, rate, years]);

  const chartData = {
    labels: ['Invested Principal', 'Total Interest'],
    datasets: [{
      data: [result?.breakdown.invested, result?.breakdown.interest],
      backgroundColor: ['#ffffff40', '#ffffff'],
      borderWidth: 0,
    }],
  };

  // --- PDF Download Logic (via HTML Print) ---
  const handleDownloadReport = () => {
    if (!result || !result.schedule || result.schedule.length === 0) {
      alert("Please calculate a result before generating the report.");
      return;
    }

    const { breakdown, schedule } = result;

    let tableRows = '';
    schedule.forEach((item: any) => {
      tableRows += `
            <tr style="border-bottom: 1px solid #eee;">
                <td style="padding: 12px; text-align: center;">${item.year}</td>
                <td style="padding: 12px; text-align: right;">₹ ${investment.toLocaleString('en-IN')}</td>
                <td style="padding: 12px; text-align: right; color: #059669;">₹ ${item.interest.toLocaleString('en-IN')}</td>
                <td style="padding: 12px; text-align: right; font-weight: bold;">₹ ${item.value.toLocaleString('en-IN')}</td>
            </tr>
        `;
    });

    const reportHTML = `
        <!DOCTYPE html>
        <html>
        <head>
            <title>Fixed Deposit (FD) Report</title>
            <style>
                body { font-family: sans-serif; margin: 0; padding: 40px; color: #333; }
                .header { background-color: #f0fdf4; padding: 20px; border-radius: 8px; margin-bottom: 30px; border-left: 5px solid #10b981; }
                .summary { display: flex; justify-content: space-between; gap: 20px; margin-bottom: 40px; }
                .summary-card { padding: 20px; border-radius: 8px; flex: 1; border: 1px solid #ddd; }
                .title { font-size: 24px; font-weight: bold; color: #059669; margin-bottom: 5px; }
                .date { font-size: 12px; color: #666; }
                h2 { font-size: 18px; color: #1f2937; border-bottom: 2px solid #059669; padding-bottom: 5px; margin-bottom: 20px; margin-top: 30px; }
                table { width: 100%; border-collapse: collapse; font-size: 14px; }
                th { background-color: #e5e7eb; padding: 10px; text-align: right; color: #4b5563; font-weight: bold; border-bottom: 2px solid #333; }
                th:first-child { text-align: center; }
                .footer { margin-top: 50px; border-top: 1px solid #ccc; padding-top: 15px; font-size: 12px; color: #666; text-align: center; }

                @media print {
                    .no-print { display: none; }
                    body { box-shadow: none; margin: 0; padding: 0; }
                }
            </style>
        </head>
        <body>
            <div class="header">
                <div class="title">Fixed Deposit (FD) Maturity Report</div>
                <div class="date">Generated by FineCalcs on: ${new Date().toLocaleDateString()}</div>
                <div style="font-size: 14px; margin-top: 10px;">Principal: ₹ ${investment.toLocaleString('en-IN')} | Rate: ${rate}% (Quarterly Compounding) | Tenure: ${years} Years</div>
            </div>

            <h2>Final Deposit Summary</h2>
            <div class="summary">
                <div class="summary-card" style="border-color: #d1d5db;">
                    <p style="font-size: 14px; color: #666; margin-bottom: 5px;">Invested Principal</p>
                    <p style="font-size: 28px; font-weight: bold; color: #1f2937;">₹ ${breakdown.invested.toLocaleString('en-IN')}</p>
                </div>
                <div class="summary-card" style="border-color: #a7f3d0; background-color: #f0fdf4;">
                    <p style="font-size: 14px; color: #059669; margin-bottom: 5px;">Total Interest Earned</p>
                    <p style="font-size: 28px; font-weight: bold; color: #059669;">₹ ${breakdown.interest.toLocaleString('en-IN')}</p>
                </div>
                <div class="summary-card" style="border-color: #34d399; background-color: #ecfdf5;">
                    <p style="font-size: 14px; color: #065f46; margin-bottom: 5px;">Total Maturity Value</p>
                    <p style="font-size: 30px; font-weight: bolder; color: #065f46;">₹ ${breakdown.total.toLocaleString('en-IN')}</p>
                </div>
            </div>

            <h2>Yearly Interest Schedule</h2>
            <table>
                <thead>
                    <tr>
                        <th style="width: 10%;">Year</th>
                        <th style="width: 30%;">Initial Principal (₹)</th>
                        <th style="width: 30%;">Cumulative Interest (₹)</th>
                        <th style="width: 30%;">Total Value (₹)</th>
                    </tr>
                </thead>
                <tbody>
                    ${tableRows}
                </tbody>
            </table>

            <div class="footer">
                This report assumes quarterly compounding. Always verify rates and compounding frequency with your bank.
            </div>

            <div class="no-print" style="margin-top: 40px; text-align: center; background: #fff; padding: 20px; border: 1px dashed #ccc;">
                <p><strong>To save as PDF:</strong> Please use your browser's print function (Ctrl+P or Cmd+P) and select "Save as PDF" as the destination.</p>
            </div>
        </body>
        </html>
    `;

    const printWindow = window.open('', '', 'height=600,width=800');
    if (printWindow) {
      printWindow.document.write(reportHTML);
      printWindow.document.close();
      printWindow.onload = () => {
        printWindow.focus();
        printWindow.print();
      };
    }
  };
  // --- END PDF Download Logic ---


  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 py-12 font-sans transition-colors duration-300">
      <div className="max-w-5xl mx-auto px-4">
        <Link href="/" className="inline-flex items-center text-sm font-bold text-slate-400 hover:text-emerald-600 dark:hover:text-emerald-400 mb-8 transition-colors group">
          <ArrowLeft className="w-4 h-4 mr-1 group-hover:-translate-x-1 transition-transform" /> Back to Home
        </Link>

        <div className="grid grid-cols-1 xl:grid-cols-12 gap-8">
          {/* LEFT: Input Section */}
          <div className="xl:col-span-5 space-y-6">
            <div>
              <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400 text-xs font-extrabold mb-4 uppercase tracking-wide">
                <ShieldCheck className="w-3 h-3" /> Fixed Income
              </div>
              <h1 className="text-4xl font-black text-slate-900 dark:text-white mb-3 tracking-tight">FD Calculator</h1>
              <p className="text-slate-500 dark:text-slate-400 font-medium leading-relaxed">
                Calculate the maturity amount and interest earned on your Fixed Deposit, assuming quarterly compounding.
              </p>
            </div>

            <div className="bg-white dark:bg-slate-900 p-8 rounded-3xl shadow-xl shadow-slate-200/60 dark:shadow-none border border-slate-100 dark:border-slate-800 transition-colors">
              <InputGroup
                label="Principal Amount (Investment)"
                value={investment}
                onChange={setInvestment}
                type="currency"
                min={1000} max={5000000} step={1000}
                variant="green"
              />
              <InputGroup
                label="Annual Interest Rate (p.a)"
                value={rate}
                onChange={setRate}
                type="percentage"
                min={1} max={15} step={0.1}
                variant="green"
              />
              <InputGroup
                label="Time Period (Years)"
                value={years}
                onChange={setYears}
                type="year"
                min={1} max={25} step={1}
                variant="green"
              />

              <div className="pt-4">
                <SaveReportButton
                  reportData={{ ...result, inputs: { investment, rate, years } }}
                  calculatorType="Fixed Deposit Calculator"
                  disabled={!result}
                />

                <button
                  onClick={handleDownloadReport}
                  className="w-full mt-4 py-3 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl font-bold text-lg flex items-center justify-center gap-2 transition-all shadow-lg shadow-emerald-500/30 hover:shadow-emerald-500/50"
                >
                  <Download className="w-5 h-5" />
                  Download PDF Report
                </button>
              </div>
            </div>
          </div>

          {/* RIGHT: Result Section */}
          <div className="xl:col-span-7">
            <div className="relative overflow-hidden bg-gradient-to-br from-emerald-600 to-teal-800 rounded-3xl p-8 sm:p-10 text-white shadow-2xl shadow-emerald-200">
              <div className="absolute top-0 right-0 -mt-20 -mr-20 w-80 h-80 bg-emerald-300 opacity-20 rounded-full blur-3xl animate-pulse"></div>
              <div className="absolute bottom-0 left-0 -mb-20 -ml-20 w-80 h-80 bg-teal-900 opacity-20 rounded-full blur-3xl"></div>

              <div className="relative z-10 grid grid-cols-1 xl:grid-cols-2 gap-8 xl:gap-12 items-center">
                <div className="w-full">
                  <p className="text-emerald-100 font-semibold mb-2 tracking-wide text-xs sm:text-sm uppercase">Total Maturity Value</p>
                  <p className="text-4xl sm:text-5xl xl:text-5xl font-black tracking-tighter mb-8 drop-shadow-sm leading-tight">
                    {formatCurrency(result?.breakdown.total || 0)}
                  </p>

                  <div className="space-y-3 sm:space-y-4">
                    <div className="bg-white/10 backdrop-blur-md rounded-2xl p-4 sm:p-5 border border-white/10 hover:bg-white/20 transition-colors">
                      <div className="flex items-center gap-3 mb-1">
                        <div className="p-1.5 bg-white/20 rounded-lg">
                          <Wallet className="w-4 h-4 text-white" />
                        </div>
                        <span className="text-xs sm:text-sm font-bold text-emerald-50">Invested Principal</span>
                      </div>
                      <p className="text-xl sm:text-2xl font-bold ml-9 sm:ml-10 tracking-tight">{formatCurrency(result?.breakdown.invested || 0)}</p>
                    </div>

                    <div className="bg-emerald-900/20 backdrop-blur-md rounded-2xl p-4 sm:p-5 border border-white/5 hover:bg-emerald-900/30 transition-colors">
                      <div className="flex items-center gap-3 mb-1">
                        <div className="p-1.5 bg-emerald-400/20 rounded-lg">
                          <ArrowUpRight className="w-4 h-4 text-emerald-200" />
                        </div>
                        <span className="text-xs sm:text-sm font-bold text-emerald-100">Total Interest</span>
                      </div>
                      <p className="text-xl sm:text-2xl font-bold ml-9 sm:ml-10 text-emerald-200 tracking-tight">{formatCurrency(result?.breakdown.interest || 0)}</p>
                    </div>
                  </div>
                </div>

                <div className="flex flex-col items-center justify-center bg-white/5 rounded-3xl p-6 sm:p-8 backdrop-blur-sm border border-white/10 shadow-inner w-full max-w-sm mx-auto xl:mx-0">
                  <div className="w-40 h-40 sm:w-48 sm:h-48 relative">
                    <Pie data={chartData} options={{
                      plugins: { legend: { display: false } },
                      elements: { arc: { borderWidth: 0 } },
                      animation: { animateScale: true }
                    }} />
                  </div>
                  <div className="mt-6 sm:mt-8 flex gap-4 sm:gap-6 text-xs sm:text-sm justify-center">
                    <div className="flex items-center gap-2">
                      <div className="w-3 h-3 rounded-full bg-white/40"></div>
                      <span className="text-emerald-100 font-medium">Principal</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="w-3 h-3 rounded-full bg-white shadow-[0_0_10px_rgba(255,255,255,0.5)]"></div>
                      <span className="text-white font-bold">Interest</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* --- SEO/Content Section --- */}
        <div className="mt-20 max-w-3xl mx-auto">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">Understanding Fixed Deposits</h2>
          <p className="text-slate-600 dark:text-slate-400">Fixed deposits offer guaranteed, steady returns and are a cornerstone of safe financial planning in India. The interest is typically compounded quarterly, meaning you earn interest on your interest four times a year, leading to faster growth than simple interest.</p>
        </div>

      </div>
    </div>
  );
}

export default function FDCalculator() {
  return (
    <Suspense fallback={<div className="min-h-screen flex items-center justify-center">Loading...</div>}>
      <FDCalculatorContent />
    </Suspense>
  );
}